### ISSUE TITLE
Null exception during first run

### ISSUE THREAD

**Issue by Bodekaer** [vuejs/vue-migration-helper#12]
Got this error when running on our project:

```
C:\Users\VueRocks\AppData\Roaming\npm\node_modules\vue-migration-helper\helpers\report-warning.js:10
  var library = rule.file.match(/([^\/]+)\/[^\/]+\.js/)[1]
   ^

TypeError: Cannot read property '1' of null
    at module.exports (C:\Users\VueRocks\AppData\Roaming\npm\node_modules\vue-migration-helper\helpers\report-warning.js:10:56)
    at C:\Users\VueRocks\AppData\Roaming\npm\node_modules\vue-migration-helper\helpers\check-for-deprecations.js:26:7
    at Array.some (native)
    at module.exports (C:\Users\VueRocks\AppData\Roaming\npm\node_modules\vue-migration-helper\helpers\check-for-deprecations.js:23:16)
    at Stream.<anonymous> (C:\Users\VueRocks\AppData\Roaming\npm\node_modules\vue-migration-helper\index.js:35:36)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at drain (C:\Users\VueRocks\AppData\Roaming\npm\node_modules\vue-migration-helper\node_modules\through\index.js:36:16)
    at Stream.stream.queue.stream.push (C:\Users\VueRocks\AppData\Roaming\npm\node_modules\vue-migration-helper\node_modules\through\index.js:45:5)
    at emit (C:\Users\VueRocks\AppData\Roaming\npm\node_modules\vue-migration-helper\node_modules\split\index.js:37:14)
```

**Comment by chrisvfritz** [comment]
This should be fixed now - see #10.

**Comment by chrisvfritz** [comment]
@Bodekaer It looks like there was a remaining bug that only affected Windows, but that should also be fixed now - can you confirm the latest version now works for you?

**Comment by Bodekaer** [comment]
Yep. It works now.
Great tool! Thanks so much for building this.

All the best,

Michael Bodekaer

**Comment by chrisvfritz** [comment]
@Bodekaer Excellent!
