### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by mxm145** [vuejs/vue-migration-helper#20]
when I run install command
```shell
npm install --global git://github.com/vuejs/vue-migration-helper.git
```

I get this

```shell
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/vuejs/vue-migration-helper.git /root/.npm/_git-remotes/git-github-com-vuejs-vue-migration-helper-git-adfefcb2: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-vuejs-vue-migration-helper-git-adfefcb2'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/vuejs/vue-migration-helper.git /root/.npm/_git-remotes/git-github-com-vuejs-vue-migration-helper-git-adfefcb2: fatal: Unable to look up github.com (port 9418) (Temporary failure in name resolution)
npm ERR! Linux 2.6.32-573.7.1.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v6.5.0/bin/node" "/root/.nvm/versions/node/v6.5.0/bin/npm" "install" "--global" "git://github.com/vuejs/vue-migration-helper.git"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/vuejs/vue-migration-helper.git /root/.npm/_git-remotes/git-github-com-vuejs-vue-migration-helper-git-adfefcb2
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-vuejs-vue-migration-helper-git-adfefcb2'...
npm ERR! fatal: Unable to look up github.com (port 9418) (Temporary failure in name resolution)
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

the npm-debug.log is
```shell
25 verbose stack Error: Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/vue
js/vue-migration-helper.git /root/.npm/_git-remotes/git-github-com-vuejs-vue-migration-helper-git-adfefcb2
25 verbose stack Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-vuejs-vue-migration-helper-git-adfefcb2
'...
25 verbose stack fatal: Unable to look up github.com (port 9418) (Temporary failure in name resolution)
25 verbose stack
25 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
25 verbose stack     at emitTwo (events.js:106:13)
25 verbose stack     at ChildProcess.emit (events.js:191:7)
25 verbose stack     at maybeClose (internal/child_process.js:877:16)
25 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
26 verbose cwd /root
27 error Linux 2.6.32-573.7.1.el6.x86_64
28 error argv "/root/.nvm/versions/node/v6.5.0/bin/node" "/root/.nvm/versions/node/v6.5.0/bin/npm" "install" "--global" "git:
//github.com/vuejs/vue-migration-helper.git"
29 error node v6.5.0
30 error npm  v3.10.3
31 error code 128
32 error Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/vuejs/vue-migratio
n-helper.git /root/.npm/_git-remotes/git-github-com-vuejs-vue-migration-helper-git-adfefcb2
32 error Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-vuejs-vue-migration-helper-git-adfefcb2'...
32 error fatal: Unable to look up github.com (port 9418) (Temporary failure in name resolution)
33 error If you need help, you may report this error at:
33 error     <https://github.com/npm/npm/issues>
34 verbose exit [ 1, true ]
```

**Comment by mxm145** [comment]
solve it, change the command to 
```shell
npm install --global https://github.com/vuejs/vue-migration-helper.git
```

**Comment by chrisvfritz** [comment]
> fatal: Unable to look up github.com (port 9418) (Temporary failure in name resolution)
npm ERR! 

It looks like it was actually just a temporary problem with either GitHub or the Internet connection.
