### ISSUE TITLE
check-for-deprecations.js -> TypeError: Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by tinchox5** [vuejs/vue-migration-helper#27]
Hi, I'm having this issue. Below the output. 
Thanks

/usr/local/lib/node_modules/vue-migration-helper/helpers/check-for-deprecations.js:43
    return ignorableExtensions[warning.type].some(function (extension) {
                                            ^
TypeError: Cannot read property 'some' of undefined
    at shouldIgnoreWarning (/usr/local/lib/node_modules/vue-migration-helper/helpers/check-for-deprecations.js:43:45)
    at /usr/local/lib/node_modules/vue-migration-helper/helpers/check-for-deprecations.js:52:21
    at Array.some (native)
    at module.exports (/usr/local/lib/node_modules/vue-migration-helper/helpers/check-for-deprecations.js:50:16)
    at Stream.<anonymous> (/usr/local/lib/node_modules/vue-migration-helper/index.js:37:38)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at drain (/usr/local/lib/node_modules/vue-migration-helper/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/usr/local/lib/node_modules/vue-migration-helper/node_modules/through/index.js:45:5)
    at emit (/usr/local/lib/node_modules/vue-migration-helper/node_modules/split/index.js:37:14)

**Comment by chrisvfritz** [comment]
@tinchox5 Can you make sure you're using the latest version of the migration helper? I don't believe this error should be possible on master.

**Comment by tinchox5** [comment]
Hi, well I've just updated it today reinstalling it as you mention in
Github. Maybe I need to uninstall the previous version before?

**Comment by chrisvfritz** [comment]
You can try it. If that doesn't work, could you jump into that file throwing the error:

``` 
/usr/local/lib/node_modules/vue-migration-helper/helpers/check-for-deprecations.js
```

And right before the line that throws, add:

```
console.log(warning.type)
```

Then let me know what the value is? The error you're seeing should only happen when `warning.type` is not one of 3 different values, but I have passing tests confirming that it should never be, which confuses me. 😅

**Comment by tinchox5** [comment]
I hope this help you:

console.log(warning.type)
    ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/vue-migration-helper/index.js:9:30
    at Request._callback (/usr/local/lib/node_modules/vue-migration-helper/helpers/check-if-outdated.js:46:5)

**Comment by chrisvfritz** [comment]
Hmm, that's strange. It says the error is coming from a completely different file. Let's try a different tact. Can you share versions of Node and NPM, as well as OS?

**Comment by tinchox5** [comment]
Of course,
npm: '3.10.3',
node: '6.4.0',
Mac OS Sierra 10.12.1

**Comment by fishenal** [comment]
same in windows
```
C:\Users\yudonghan\AppData\Roaming\npm\node_modules\vue-migration-helper\helpers\check-for-deprecations.js:43
    return ignorableExtensions[warning.type].some(function (extension) {
                                            ^

TypeError: Cannot read property 'some' of undefined
    at shouldIgnoreWarning (C:\Users\yudonghan\AppData\Roaming\npm\node_modules\vue-migration-helper\helpers\check-for-deprecations.js:43:45)
    at C:\Users\yudonghan\AppData\Roaming\npm\node_modules\vue-migration-helper\helpers\check-for-deprecations.js:52:21
    at Array.some (native)
    at module.exports (C:\Users\yudonghan\AppData\Roaming\npm\node_modules\vue-migration-helper\helpers\check-for-deprecations.js:50:16)
    at Stream.<anonymous> (C:\Users\yudonghan\AppData\Roaming\npm\node_modules\vue-migration-helper\index.js:37:38)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at drain (C:\Users\yudonghan\AppData\Roaming\npm\node_modules\vue-migration-helper\node_modules\through\index.js:36:16)
    at Stream.stream.queue.stream.push (C:\Users\yudonghan\AppData\Roaming\npm\node_modules\vue-migration-helper\node_modules\through\index.js:45:5)
    at emit (C:\Users\yudonghan\AppData\Roaming\npm\node_modules\vue-migration-helper\node_modules\split\index.js:37:14)

```
npm 3.3.12
node 5.1.0

win7 git-bash

**Comment by chrisvfritz** [comment]
OK, I believe it should be fixed now. Can you both try reinstalling?

**Comment by fishenal** [comment]
it's ok for me, thank you!

**Comment by tinchox5** [comment]
Yeah! Its works for me too.
Thank you

2016-11-02 3:25 GMT-04:00 yu.dh <notifications@github.com>:

**Comment by chrisvfritz** [comment]
Great! Thanks for reporting it.
